### ISSUE TITLE
All XULRunner files have the executable bit set

### ISSUE THREAD

**Issue by freaktechnik** [nightingale-media-player/nightingale-deps#17]
Apparently all the files in the XULRunner dep have the executable bit set. I don't know if it's required, however it causes warnings in the debian package. If this is wanted we can change the executable bit when building the debian package.

**Comment by AntoineTurmel** [comment]
I think it's required for libraries and binaries, better look at documentation to be sure.

**Comment by freaktechnik** [comment]
Yes, but not for CSS files and similar.

**Comment by johnmurrayvi** [comment]
FWIW the permissions on the xulrunner files are changed here: [make-xulrunner-tarball.sh#L42](https://github.com/nightingale-media-player/nightingale-deps/blob/xul-192-new/xulrunner-1.9.2/make-xulrunner-tarball.sh#L42)

**Comment by freaktechnik** [comment]
I don't know what it exactlty does, but there's also a statement which sets some files to 644, which is the desired setting for non-executables.

**Comment by darealshinji** [comment]
@AntoineTurmel On GNU/Linux shared libraries should be set to non-executable/0644. http://lintian.debian.org/tags/shlib-with-executable-bit.html

ld.so seems to be the only exception, as described in the lintian tag overrides file:
 # ld.so must be executable, otherwise the system will not work
libc6: shlib-with-executable-bit */ld-2.17.so 0755

**Comment by johnmurrayvi** [comment]
I think this issue is because it could be tedious to go through and set the permissions individually.
make-xulrunner-tarball.sh gets called from [xr_pack_deps.sh#L33](https://github.com/nightingale-media-player/nightingale-deps/blob/xul-192-new/xulrunner-1.9.2/xr_pack_deps.sh#L33).
There must be a reason the permissions are being "fixed" in the first place, but the [git history](https://github.com/nightingale-media-player/nightingale-deps/commits/xul-192-new/xulrunner-1.9.2/make-xulrunner-tarball.sh) doesn't help.

**Comment by johnmurrayvi** [comment]
I think this should be fixed by https://github.com/nightingale-media-player/nightingale-deps/commit/d7523339512baef7f46530320e7c212c5620836a
